import csv
import os

# Product classes for each economy
from CapitalistProduct import CapitalistProduct
from LaborTimeProduct import LaborTimeProduct 

# Note: the prices are in ratios, not in any currency. 
def build_ce_map(csv_path):
    """
    Build the CE commodity → price map using the equilibrium row
    from trajectories_with_equilibrium.csv.
    """
    # Ensure CSV file exists
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"CSV not found at: {csv_path}")

    eq_row = None  # Will store the equilibrium row

    # Read CSV as a dictionary per row
    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Identify the unique equilibrium row
            if row.get("is_equilibrium_step") == "1":
                eq_row = row
                break

    # Safety check: equilibrium must exist
    if eq_row is None:
        raise ValueError("No equilibrium row found (is_equilibrium_step == 1).")

    ce_map = {}

    # Build CE product objects for A–Z using equilibrium prices
    for i in range(26):
        name = chr(ord("A") + i)  # Convert 0→A, 1→B, ..., 25→Z
        price_key = f"equilibrium_price_{name}"
        output_key = f"equilibrium_output_{name}"

        price_val = eq_row.get(price_key)
        output_val = eq_row.get(output_key)

        if price_val is None or price_val == "":
            raise ValueError(f"Missing {price_key} in equilibrium row.")
        if output_val is None or output_val == "":
            raise ValueError(f"Missing {output_key} in equilibrium row.")

        eq_price = float(price_val)
        eq_output = float(output_val)

        current_price = eq_price
        current_output = eq_output

        ce_map[name] = CapitalistProduct(
            name,
            current_price,
            current_output,
            eq_price,
            eq_output
        )

    return ce_map


def build_lte_map():
    """
    Build a placeholder LTE commodity → labor-time map.
    Real LTE values can replace this later.
    """
    lte_map = {}

    # Assign constant placeholder labor time to each commodity
    for i in range(26):
        name = chr(ord("A") + i)
        labor_time = 10.0  # Placeholder value
        lte_map[name] = LaborTimeProduct(name, labor_time)

    return lte_map


def print_maps(ce_map, lte_map):
    """
    Print both CE and LTE maps in a readable format.
    """
    print("\n--- CE map (commodity -> CapitalistProduct) ---")
    for name in sorted(ce_map.keys()):
        print(name, "->", ce_map[name])

    print("\n--- LTE map (commodity -> LaborTimeProduct) ---")
    for name in sorted(lte_map.keys()):
        print(name, "->", lte_map[name])

# Lists for import/export         
CE_Import = []
LTE_Import = []
CE_Export = []
LTE_Export = []

# Placeholder function
def Trade(ce_map, lte_map, time_step):
    """
    Called every simulation time step.

    Arguments:
        ce_map  : CE commodity -> CapitalistProduct map
        lte_map : LTE commodity -> LaborTimeProduct map
        time_step : current simulation time step

    Updates:
        CE_Import, LTE_Import, CE_Export, LTE_Export
    """

    # TODO:
    # 1. Check which products CE is missing - add to CE_Import
    # 2. Check which products LTE is missing - add to LTE_Import
    # 3. Detect shortages (CE) - add to CE_Import
    # 4. Detect social needs (LTE) - add to LTE_Import
    # 5. Detect surpluses (CE) - add to CE_Export
    # 6. Detect surpluses (LTE) - add to LTE_Export
    # 7. Remove items when conditions disappear
    # 8. Use a trade algorithm to determine which product should be traded for what, how much it should be traded, and for what price 
    
    # Questions:
    # Need to ask how to get data from LTE 
    # How to develop an algorithm for trading? (Or we can do this next week?)
    # (Note: If can't get data from LTE, I need data from LTE for testing if the trading function actually work. What kind of data should I use?) 
    # What is a shortage? Is it when price > eq_price, output < eq_output, or both? I think it's both since it should happen at the same time. 

    print(f"[t={time_step}] Trade() executed")

if __name__ == "__main__":
    # Path to equilibrium data generated by event-based simulation
    csv_path = os.path.join(
        "..",
        "Event-Based Simulation",
        "graphs",
        "trajectories_with_equilibrium.csv"
    )

    # Build CE and LTE maps
    ce_map = build_ce_map(csv_path)
    lte_map = build_lte_map()

    # Display results
    print_maps(ce_map, lte_map)
