#pragma once

#include <cmath>

enum Ability { ABILITY_1, ABILITY_2, ABILITY_3, NUM_ABILITIES }; 

const int DAY = 24;
const int WEEK = DAY * 7;
const int MONTH = DAY * 30;
const int YEAR = DAY * 365;

// Threshold for productivity before lowering working hours
const double PRODUCTIVITY_THRESHOLD = 60.0;
const int INITIAL_WORK_HOURS_DAILY = 8;
const int INITIAL_WORK_DAYS_WEEKLY = 5;
const int INITIAL_WORK_WEEK = INITIAL_WORK_HOURS_DAILY * \
                              INITIAL_WORK_DAYS_WEEKLY;

const int STARTING_NUM_PEOPLE = 1000;
const int STARTING_NUM_PRODUCTS = 100;
// const int STARTING_NUM_PRODUCTS = 16;
const int STARTING_NUM_PRODUCERS = STARTING_NUM_PRODUCTS;
const int STARTING_NUM_DISTRIBUTORS = STARTING_NUM_PRODUCTS;

const int INITIAL_AGE = 17 * YEAR;
const double RANDOM_RETIREMENT_CHANCE = 8.3e-7;
const int GUARANTEED_RETIREMENT_AGE = 67 * YEAR;
const double AVERAGE_RETIREMENT_AGE = (
        1 - pow(1 - RANDOM_RETIREMENT_CHANCE, GUARANTEED_RETIREMENT_AGE)) /
    RANDOM_RETIREMENT_CHANCE +
    INITIAL_AGE; // approx 62 years in hours

const int NUM_BASE_PRODUCTS = STARTING_NUM_PRODUCTS / 20;
const int PRODUCT_ORDER_SIZE_MIN = 1;
const int PRODUCT_ORDER_SIZE_MAX = 1000;
const int PRODUCT_NUM_INPUTS_MIN = 0;
const int PRODUCT_NUM_INPUTS_MAX = 10;
const double PRODUCT_INPUT_PER_UNIT_MIN = 0.01;
const double PRODUCT_INPUT_PER_UNIT_MAX = 0.25;
const double PRODUCT_INPUT_EPSILON = 0.0001;
const int PRODUCT_LABOR_PER_UNIT_MIN = 1;
const int PRODUCT_LABOR_PER_UNIT_MAX = INITIAL_WORK_WEEK; 
const double PRODUCT_CONSUMPTION_FREQUENCY_MIN = 1.0 / (2 * WEEK);
const double PRODUCT_CONSUMPTION_FREQUENCY_MAX = 1;

const int FIRM_TRAINING_TIME = INITIAL_WORK_HOURS_DAILY * WEEK / DAY;
const int FIRM_STOCKPILE_DURATION = MONTH;
const int FIRM_DEMAND_WINDOW = WEEK;
const double FIRM_INITIAL_INVENTORY_MULTIPLIER = 2;

const int DRAFT_ORDER_REJECTED = -1;

const double PERSON_FREQUENCY_MULTIPLIER_STDDEV = 0.1;
const double PERSON_SHOPPING_MULTIPLIER_STDDEV = 0.1;
const int PERSON_SHOPPING_PERIOD = WEEK;
const double PERSON_SHOPPING_OFFSET_STDDEV = DAY / 2.0;
const double PERSON_ABILITY_STDDEV = 0.2;

const double UNHEALTHY_PRODUCTIVITY = 0.5;
const double DAILY_SICKNESS_CHANCE = 0.01;
const double DAILY_RECOVERY_CHANCE = 0.1;

const int PERSON_ABILITY_COUNT_MAX = 3;
const int PRODUCT_ABILITY_COUNT_MAX = 3;

