#pragma once

#include <cmath>

enum Ability { ABILITY_1, ABILITY_2, ABILITY_3, NUM_ABILITIES }; 

const int DAY = 24;
const int WEEK = DAY * 7;
const int MONTH = DAY * 30;
const int YEAR = DAY * 365;

// Threshold for productivity before lowering working hours
const double PRODUCTIVITY_THRESHOLD = 60.0;
const int INITIAL_WORK_HOURS_DAILY = 8;
const int INITIAL_WORK_WEEK = INITIAL_WORK_HOURS_DAILY * 5;

const int STARTING_NUM_PEOPLE = 1000;
const int STARTING_NUM_PRODUCTS = 100;
const int STARTING_NUM_PRODUCERS = STARTING_NUM_PRODUCTS;
const int STARTING_NUM_DISTRIBUTORS = STARTING_NUM_PRODUCTS;

const int INITIAL_AGE = 17 * YEAR;
const double RANDOM_RETIREMENT_CHANCE = 8.3e-7;
const int GUARANTEED_RETIREMENT_AGE = 67 * YEAR;
const double AVERAGE_RETIREMENT_AGE = (1 -
        pow(1 - RANDOM_RETIREMENT_CHANCE, GUARANTEED_RETIREMENT_AGE)) / RANDOM_RETIREMENT_CHANCE
+ INITIAL_AGE; // approx 62 years in hours

const int PRODUCT_ORDER_SIZE_MIN = 1;
const int PRODUCT_ORDER_SIZE_MAX = 1000;
const int PRODUCT_NUM_INPUTS_MIN = 0;
const int PRODUCT_NUM_INPUTS_MAX = STARTING_NUM_PRODUCTS / 20;
const int PRODUCT_NUM_INPUT_UNITS_MIN = 1;
const int PRODUCT_NUM_INPUT_UNITS_MAX = 100;
const int PRODUCT_LABOR_PER_UNIT_MIN = 1;
const int PRODUCT_LABOR_PER_UNIT_MAX = INITIAL_WORK_WEEK; 
const double PRODUCT_CONSUMPTION_FREQUENCY_MIN = 1.0 / (2 * WEEK);
const double PRODUCT_CONSUMPTION_FREQUENCY_MAX = 1;

const int FIRM_TRAINING_TIME = INITIAL_WORK_HOURS_DAILY * WEEK / DAY;

const int DRAFT_ORDER_REJECTED = -1;

const double PERSON_FREQUENCY_MULTIPLIER_STDDEV = 0.1;
const double PERSON_SHOPPING_MULTIPLIER_STDDEV = 0.1;
const int PERSON_SHOPPING_PERIOD = WEEK;
const double PERSON_SHOPPING_OFFSET_STDDEV = DAY / 2.0;
const double PERSON_ABILITY_STDDEV = 0.2;

const int PERSON_ABILITY_COUNT_MAX = 3;
const int PRODUCT_ABILITY_COUNT_MAX = 3;

